<?php

namespace app\base;

use yii\web\Controller;
use yii\web\HttpException;

class BaseWebController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws HttpException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if(\Yii::$app->user->isGuest){
            throw new HttpException(401,'need authorization');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    
    public function afterAction($action, $result)
    {

        \Yii::$app->session->setFlash('pageBack',\Yii::$app->request->pathInfo);

        return parent::afterAction($action, $result);
    }
}